target 'ChronoSync' do
  platform :ios, '12.0'
  use_frameworks!

  pod 'Result', '4.1.0'
  pod 'Swinject', '2.5.0'
  pod 'SwinjectStoryboard', '2.1.0'

  target 'ChronoSyncTests' do
    inherit! :search_paths
    pod 'Quick', '1.3.2'
    pod 'Nimble', '7.3.1'
    pod 'Spry', '3.2.3'
    pod 'Spry+Nimble', '3.2.3'
  end

end
