target 'ChronoSync' do
  platform :ios, '13.2'
  use_frameworks!

  pod 'Alamofire', '5.1.0'
  pod 'Nuke', '9.0.0-rc.1' #:git => 'https://github.com/kean/Nuke.git', :commit => '6001489d22e5f41a4956c1b6cd4cf7cbe8f44dff'
  pod 'RxRelay', '5.1.1'
  pod 'RxSwift', '5.1.1'
  pod 'Swinject', :path => '/Users/codyv/Documents/Nope/KI/Swinject' #'2.7.1'
  pod 'SwinjectStoryboard', :path => '/Users/codyv/Documents/Nope/KI/SwinjectStoryboard' #:git => 'https://github.com/Swinject/SwinjectStoryboard.git', :commit => '0ca45c83a8aa398c153d8a036c95abb4343cfa0c'

  target 'ChronoSyncTests' do
    inherit! :search_paths
    pod 'KIF', '3.7.9'
    pod 'KIF/IdentifierTests', '3.7.9'
    pod 'Nimble', '9.0.0-beta.1'
    pod 'OHHTTPStubs/Swift', '9.0.0'
    pod 'Quick', '2.2.0'
    pod 'RxBlocking', '5.1.1'
    pod 'RxTest', '5.1.1'
    pod 'Spry', :path => '/Users/codyv/Documents/Nope/KI/Spry' #'3.2.3'
    pod 'Spry+Nimble', :path => '/Users/codyv/Documents/Nope/KI/Spry' #'3.2.3'
  end

end
